export const sections = [
  { label: 'Opening', start: 1 },
  { label: 'Realities', start: 6 },
  { label: 'Motivations', start: 13 },
  { label: 'STAR Value', start: 15 },
  { label: 'Retention', start: 20 },
  { label: 'Visibility', start: 28 },
  { label: 'Development', start: 34 },
  { label: 'Impact', start: 37 },
  { label: 'Recognition', start: 42 },
  { label: 'Region Role', start: 45 },
  { label: 'Action', start: 50 },
  { label: 'Close', start: 54 },
]

export const slides = [
  {
    number: 1,
    section: 'Opening',
    kind: 'title',
    tone: 'gold',
    eyebrow: 'PICPA STAR Membership Blueprint',
    title: 'The STAR Region Membership Blueprint',
    subtitle:
      'Empowering PICPA Members: The Role of Regions and Chapters in Membership Development',
    strapline:
      'Building Value | Creating Connections | Advancing the Profession | Inspiring Belonging',
  },
  {
    number: 2,
    section: 'Opening',
    kind: 'list',
    tone: 'forest',
    title: 'Session Objectives',
    lead: 'At the end of the session, participants should be able to:',
    items: [
      'Understand the current membership realities affecting PICPA chapters',
      'Identify barriers to membership growth, retention, and engagement',
      'Recognize the different motivations of members',
      'Appreciate the role of Regions and Chapters in membership development',
      'Identify practical strategies to strengthen membership',
      'Commit to actionable initiatives within the next 90 days',
    ],
  },
  {
    number: 3,
    section: 'Opening',
    kind: 'reflection',
    tone: 'clay',
    title: 'Opening Reflection',
    prompt: 'If PICPA disappeared tomorrow...',
    lead: 'What would CPAs miss the most?',
    items: [
      'CPD',
      'Networking',
      'Mentorship',
      'Advocacy',
      'Leadership opportunities',
      'Friendships',
      'Professional identity',
    ],
  },
  {
    number: 4,
    section: 'Opening',
    kind: 'contrast',
    tone: 'teal',
    title: 'Membership Development Is Not About Numbers',
    left: {
      title: 'Membership is not only about',
      items: ['Dues', 'Attendance', 'Renewal', 'Databases', 'Reports'],
    },
    right: {
      title: 'Membership development is about',
      items: [
        'Value',
        'Relationships',
        'Opportunities',
        'Visibility',
        'Belonging',
        'Professional identity',
      ],
    },
  },
  {
    number: 5,
    section: 'Opening',
    kind: 'flow',
    tone: 'plum',
    title: 'Membership Development Journey',
    emphasis: 'journey',
    flow: ['Recruit', 'Retain', 'Engage', 'Develop', 'Belong', 'Lead', 'Advocate'],
    lead: 'Membership is a journey, not a transaction.',
  },
  {
    number: 6,
    section: 'Realities',
    kind: 'list',
    tone: 'leaf',
    title: 'The Four Membership Realities',
    lead: 'Every chapter has:',
    items: [
      'CPAs who never join',
      'Members who do not renew',
      'Members who renew but remain inactive',
      'Active members who stay',
    ],
  },
  {
    number: 7,
    section: 'Realities',
    kind: 'list',
    tone: 'gold',
    title: 'Why CPAs Never Join',
    label: 'Common reasons',
    emphasis: 'common-reasons',
    items: [
      'Cost concerns',
      'Lack of awareness',
      'No personal invitation',
      'Limited perceived value',
      'Employer does not subsidize dues',
      "Weak understanding of PICPA's role",
      'No emotional connection to the organization',
    ],
  },
  {
    number: 8,
    section: 'Realities',
    kind: 'list',
    tone: 'forest',
    title: 'Why Members Do Not Renew',
    label: 'Common reasons',
    items: [
      'No perceived return on investment',
      'Membership viewed only for compliance',
      'Competing financial priorities',
      'Limited engagement',
      'Programs do not address their needs',
      'Changing professional priorities',
    ],
  },
  {
    number: 9,
    section: 'Realities',
    kind: 'list',
    tone: 'clay',
    title: 'Why Members Remain Inactive',
    label: 'Common reasons',
    items: [
      'Busy work schedules',
      'Family commitments',
      'Distance and travel limitations',
      'Activities not aligned with interests',
      'Lack of meaningful role',
      'No personal follow-up from the chapter',
    ],
  },
  {
    number: 10,
    section: 'Realities',
    kind: 'list',
    tone: 'teal',
    title: 'Why Active Members Stay',
    label: 'Common reasons',
    items: [
      'Professional growth',
      'Networking',
      'Mentorship',
      'Recognition',
      'Friendships',
      'Leadership opportunities',
      'Sense of belonging',
    ],
  },
  {
    number: 11,
    section: 'Realities',
    kind: 'list',
    tone: 'plum',
    title: 'What Chapters Are Telling Us',
    label: 'Common findings from chapter responses',
    dense: true,
    emphasis: 'findings',
    items: [
      'Membership sponsorship is needed, especially for newly passed CPAs.',
      'Limited cross-industry collaboration affects engagement.',
      'Attracting new CPAs while retaining existing members remains difficult.',
      'Demanding work schedules result in low attendance and limited volunteer involvement.',
      'Programs must evolve with digital finance, analytics, and changing accounting roles.',
      'Employers are reducing subsidies for dues, training, and professional membership.',
      'Regions and National PICPA are expected to strengthen advocacy and public visibility.',
      'Members want stronger belonging and professional identity.',
    ],
  },
  {
    number: 12,
    section: 'Realities',
    kind: 'statement',
    tone: 'leaf',
    title: 'The Most Important Insight',
    emphasis: 'insight',
    statements: [
      { lead: 'People join', bridge: 'for', focus: 'value.' },
      { lead: 'People stay', bridge: 'for', focus: 'relationships.' },
      { lead: 'People lead', bridge: 'because they', focus: 'belong.' },
    ],
  },
  {
    number: 13,
    section: 'Motivations',
    kind: 'list',
    tone: 'gold',
    title: 'Members Join for Different Reasons',
    lead: 'Not all CPAs join PICPA for the same reason.',
    label: 'Some members are motivated by',
    items: [
      'Recognition',
      'Socialization',
      'Leadership opportunities',
      'Professional growth',
      'Mentorship',
      'Technical learning',
      'Advocacy',
      'Community service',
      'Business or career opportunities',
    ],
    noteStyle: 'takeaway',
    noteSegments: [
      { text: 'Membership development', emphasis: true },
      { text: ' becomes more effective when chapters ' },
      { text: 'understand and respond', emphasis: true },
      { text: ' to ' },
      { text: 'different member motivations', emphasis: true },
      { text: '.' },
    ],
    note:
      'Membership development becomes more effective when chapters understand and respond to different member motivations.',
  },
  {
    number: 14,
    section: 'Motivations',
    kind: 'table',
    tone: 'forest',
    title: 'Turning Member Motivations Into Opportunities',
    tableStyle: 'motivation-map',
    columns: ['Member Motivation', 'Chapter Opportunity'],
    rows: [
      ['Recognition', 'Awards, member features, Wall of Excellence'],
      ['Socialization', 'Fellowship, networking, chapter gatherings'],
      ['Leadership', 'Committees, officer pipeline, project leadership'],
      ['Learning', 'CPD, technical sessions, skills development'],
      ['Mentorship', 'STAR Connect, senior-young CPA pairing'],
      ['Service', 'Community impact projects, financial literacy'],
      ['Advocacy', 'Public forums, policy discussions, professional representation'],
      ['Career/Business', 'Referrals, partnerships, professional exposure'],
    ],
  },
  {
    number: 15,
    section: 'STAR Value',
    kind: 'orbit',
    tone: 'clay',
    title: 'The STAR Membership Ecosystem',
    lead: 'The STAR Region Membership Blueprint is built on six strategic areas:',
    items: ['Value', 'Connection', 'Visibility', 'Development', 'Advocacy', 'Recognition'],
  },
  {
    number: 16,
    section: 'STAR Value',
    kind: 'hero',
    tone: 'teal',
    emphasis: 'star-id-value',
    title: 'STAR ID: Everyday Proof of Value',
    lead: 'Make membership visible, useful, and easy to explain.',
    feature: {
      title: 'From membership record to daily touchpoint',
      body: 'A practical card that connects belonging with benefits members can see and use.',
      tags: ['Visible', 'Useful', 'Local', 'Repeatable'],
    },
    items: [
      {
        label: 'Visible',
        title: 'Show belonging',
        text: 'Members can identify with the STAR community beyond seminars and formal events.',
      },
      {
        label: 'Useful',
        title: 'Access privileges',
        text: 'Partner benefits make membership value concrete between CPD activities.',
      },
      {
        label: 'Repeatable',
        title: 'Start conversations',
        text: 'Each use creates a reason to invite, renew, reconnect, or recognize members.',
      },
    ],
  },
  {
    number: 17,
    section: 'STAR Value',
    kind: 'acronym',
    tone: 'plum',
    title: 'STAR ID Meaning',
    items: [
      ['S', 'Savings', 'Discounts and partner privileges'],
      ['T', 'Training', 'CPD and professional learning'],
      ['A', 'Access', 'Mentorship, networking, and opportunities'],
      ['R', 'Recognition', 'Awards, leadership opportunities, and member visibility'],
    ],
  },
  {
    number: 18,
    section: 'STAR Value',
    kind: 'groups',
    tone: 'leaf',
    title: 'STAR ID Partnerships',
    groups: [
      {
        title: 'Possible partners',
        items: [
          'Coffee shops and milk tea shops',
          'Restaurants and food establishments',
          'Hotels and resorts',
          'Pharmacies and wellness centers',
          'Printing shops and bookstores',
          'Technology stores and service providers',
          'Review centers',
          'Professional service providers',
        ],
      },
      {
        title: 'Example',
        items: [
          '5% discount at a partner milk tea shop',
          '10% discount at a partner restaurant',
          'Special rates at partner hotels or resorts',
        ],
      },
    ],
  },
  {
    number: 19,
    section: 'STAR Value',
    kind: 'list',
    tone: 'gold',
    title: 'Why STAR ID Matters',
    lead: 'The STAR ID creates:',
    items: [
      'Tangible value',
      'Membership visibility',
      'Member retention',
      'Daily reminders of membership benefits',
      'Local business partnerships',
      'A stronger sense of professional identity',
    ],
  },
  {
    number: 20,
    section: 'Retention',
    kind: 'groups',
    tone: 'forest',
    title: 'STAR Welcome and Re-Invitation Packet',
    lead: 'Every member should feel personally welcomed.',
    emphasis: 'packet-trio',
    groups: [
      {
        title: 'The STAR Region may introduce',
        items: [
          { name: 'STAR Welcome Packet', audience: 'New members' },
          {
            name: 'STAR Re-Invitation Packet',
            audience: 'Old, returning, inactive, or lapsed members',
          },
          { name: 'STAR Renewal Appreciation Packet', audience: 'Continuing members' },
        ],
      },
    ],
  },
  {
    number: 21,
    section: 'Retention',
    kind: 'list',
    tone: 'clay',
    title: 'STAR Welcome Packet for New Members',
    label: 'The STAR Welcome Packet may include',
    items: [
      'Welcome letter from the Region or Chapter',
      'Membership guide',
      'Chapter introduction',
      'Calendar of activities',
      'STAR ID information',
      'Mentorship invitation',
      'List of member benefits',
      'Invitation to join a committee or community group',
      'Contact details of chapter officers',
    ],
  },
  {
    number: 22,
    section: 'Retention',
    kind: 'list',
    tone: 'teal',
    title: 'STAR Re-Invitation Packet for Old or Inactive Members',
    label: 'The STAR Re-Invitation Packet may include',
    items: [
      'Re-welcome message',
      'Updated chapter programs',
      'New membership benefits',
      'STAR ID privileges',
      'Volunteer and leadership opportunities',
      'Invitation to reconnect',
      'Short survey asking how PICPA can better serve them',
    ],
  },
  {
    number: 23,
    section: 'Retention',
    kind: 'list',
    tone: 'plum',
    title: 'STAR Renewal Appreciation Packet',
    label: 'For continuing members, chapters may provide',
    items: [
      'Renewal thank-you message',
      'Updated calendar of activities',
      'STAR ID partner directory',
      'Invitation to participate in committees',
      'Membership milestone recognition notice',
      'Opportunities for mentorship, leadership, or community service',
    ],
  },
  {
    number: 24,
    section: 'Retention',
    kind: 'groups',
    tone: 'leaf',
    title: 'STAR Sponsorship Program',
    lead: 'Adopt-A-New-CPA',
    groups: [
      {
        title: 'Possible sponsors',
        items: [
          'Senior CPAs',
          'Accounting firms',
          'Chapters',
          'Corporate partners',
          'Business supporters',
        ],
      },
      {
        title: 'Purpose',
        items: [
          'Reduce financial barriers',
          'Welcome newly licensed CPAs',
          'Create early emotional connection',
          'Strengthen intergenerational support',
        ],
      },
    ],
  },
  {
    number: 25,
    section: 'Retention',
    kind: 'list',
    tone: 'gold',
    title: 'STAR Connect',
    lead: 'Regional Mentorship and Networking Platform',
    label: 'STAR Connect may link',
    items: [
      'Young CPAs',
      'Senior CPAs',
      'Public practitioners',
      'Government CPAs',
      'Corporate leaders',
      'Academe',
      'Entrepreneurs',
      'Chapter officers',
    ],
  },
  {
    number: 26,
    section: 'Retention',
    kind: 'list',
    tone: 'forest',
    title: 'STAR Communities',
    lead: 'Build communities, not just events.',
    label: 'Suggested communities',
    items: [
      'Public Practice Community',
      'Government CPA Community',
      'Corporate CPA Community',
      'Academe Community',
      'Young CPA Community',
      'CPA Entrepreneurs Community',
      'Digital Finance and Analytics Community',
    ],
  },
  {
    number: 27,
    section: 'Retention',
    kind: 'hero',
    tone: 'clay',
    emphasis: 'invitation-campaign',
    title: 'Every CPA Gets a Personal Invitation',
    lead: 'Turn recruitment into a clear officer commitment.',
    formula: [
      { value: '10', label: 'chapter officers' },
      { value: '10', label: 'personal invitations each' },
      { value: '100', label: 'potential members reached annually' },
    ],
    items: [
      {
        label: 'Identify',
        text: 'Build a short list of never-joined, inactive, and newly licensed CPAs.',
      },
      {
        label: 'Invite',
        text: 'Use a direct message, call, or coffee invite instead of a general announcement.',
      },
      {
        label: 'Follow up',
        text: 'Reconnect within seven days and offer a concrete next activity or role.',
      },
    ],
  },
  {
    number: 28,
    section: 'Visibility',
    kind: 'statement',
    tone: 'teal',
    title: 'STAR Standard Bearers',
    emphasis: 'standard-bearer',
    statements: [
      { label: 'Honor', text: 'Carrying the honor of the profession.' },
      {
        label: 'Visibility',
        text: 'Every member becomes a visible ambassador of PICPA and the STAR Region.',
      },
    ],
  },
  {
    number: 29,
    section: 'Visibility',
    kind: 'flow',
    tone: 'plum',
    emphasis: 'visibility-growth',
    title: 'Visibility Creates Membership Growth',
    lead: 'People join organizations they can see, trust, and proudly represent.',
    thesis: {
      title: 'Visibility is proof of value.',
      body: 'When chapter work is seen consistently, PICPA becomes easier to trust, easier to recommend, and easier to join.',
    },
    flow: [
      {
        label: 'Seen',
        title: 'Visibility',
        text: 'Members and non-members repeatedly see chapter activity, service, and professional value.',
      },
      {
        label: 'Known',
        title: 'Credibility',
        text: 'Consistent presence shows that the chapter is active, organized, and relevant.',
      },
      {
        label: 'Trusted',
        title: 'Trust',
        text: 'CPAs become more willing to attend, ask questions, renew, or accept an invitation.',
      },
      {
        label: 'Shared',
        title: 'Influence',
        text: 'Visible members and partners become informal ambassadors for the organization.',
      },
      {
        label: 'Joined',
        title: 'Membership Growth',
        text: 'Visibility turns interest into belonging, referrals, retention, and new members.',
        outcome: true,
      },
    ],
  },
  {
    number: 30,
    section: 'Visibility',
    kind: 'list',
    tone: 'leaf',
    title: 'STAR Standard Bearer Program',
    label: 'Visibility materials may include',
    items: [
      'Stickers',
      'Pins',
      'Polo shirts',
      'Tumblers',
      'Lanyards',
      'Social media frames',
      'Office displays',
      'Event backdrops',
      'Email signatures',
      'Presentation templates',
    ],
  },
  {
    number: 31,
    section: 'Visibility',
    kind: 'groups',
    tone: 'gold',
    title: 'STAR Stories',
    lead: 'Turn member experiences into visible chapter identity.',
    body: 'Feature members regularly, not only officers.',
    emphasis: 'story-board',
    feature: {
      label: 'Member feature plate',
      title: 'One CPA. One Story.',
      text: 'A recurring story format that makes ordinary members visible.',
    },
    groups: [
      {
        title: 'Interview prompts',
        items: [
          { label: 'Join', question: 'Why did you join PICPA?' },
          { label: 'Stay', question: 'Why do you stay?' },
          { label: 'Pride', question: 'What are you proud of as a CPA?' },
          { label: 'Impact', question: 'How has PICPA helped you?' },
          { label: 'Message', question: 'What message would you give to young CPAs?' },
        ],
      },
    ],
  },
  {
    number: 32,
    section: 'Visibility',
    kind: 'list',
    tone: 'forest',
    title: 'Introducing the PICPA STAR Page',
    lead: 'A strong membership strategy needs a strong digital platform.',
    label: 'The PICPA STAR Page will help showcase',
    items: [
      'Professional value',
      'Member stories',
      'Chapter activities',
      'Community impact',
      'Membership opportunities',
      'STAR ID partners',
      'STAR Standard Bearers',
      'Recognition programs',
    ],
    note: 'This will be further introduced by the Co-Chairman after this discussion.',
  },
  {
    number: 33,
    section: 'Visibility',
    kind: 'ratio',
    tone: 'clay',
    title: 'Content Strategy for the PICPA STAR Page',
    lead: 'The 70-20-10 Rule',
    items: [
      ['70%', 'Professional Value', 'Technical updates, career insights, practical tips, learning opportunities'],
      ['20%', 'Community Stories', 'Member features, chapter wins, volunteer stories, impact stories'],
      ['10%', 'Membership Promotion', 'Joining, renewal, benefits, and calls to action'],
    ],
  },
  {
    number: 34,
    section: 'Development',
    kind: 'list',
    tone: 'teal',
    title: 'Young CPA Development Program',
    label: 'Focus areas',
    items: [
      'Leadership development',
      'Mentorship',
      'Career growth',
      'Networking',
      'Personal branding',
      'Digital finance and analytics exposure',
      'Public speaking',
      'Professional confidence building',
    ],
  },
  {
    number: 35,
    section: 'Development',
    kind: 'list',
    tone: 'plum',
    title: 'Every Member Has a Role',
    label: 'Possible roles',
    items: [
      'Volunteer',
      'Speaker',
      'Mentor',
      'Ambassador',
      'Committee member',
      'Campus liaison',
      'Community trainer',
      'STAR ID partner coordinator',
      'STAR Story contributor',
    ],
    note: 'People support what they help build.',
  },
  {
    number: 36,
    section: 'Development',
    kind: 'flow',
    tone: 'leaf',
    title: 'Leadership Pipeline',
    flow: [
      'Member',
      'Volunteer',
      'Committee Member',
      'Committee Chair',
      'Officer',
      'Chapter President',
      'Regional Leader',
    ],
    lead: 'Membership development should also develop future leaders.',
  },
  {
    number: 37,
    section: 'Impact',
    kind: 'statement',
    tone: 'gold',
    title: 'Beyond Charity',
    statements: [
      'Community engagement is not only about outreach or donations.',
      'PICPA must be visible through professional expertise.',
      'Our knowledge is one of our strongest forms of service.',
    ],
  },
  {
    number: 38,
    section: 'Impact',
    kind: 'list',
    tone: 'forest',
    title: 'STAR Community Impact Program',
    label: 'Possible quarterly initiatives',
    items: [
      'Financial literacy',
      'Tax education',
      'SME clinics',
      'Entrepreneurship seminars',
      'Cooperative development',
      'School career talks',
      'Governance awareness',
      'Budget and financial management orientation',
      'Internal control awareness for organizations',
    ],
  },
  {
    number: 39,
    section: 'Impact',
    kind: 'list',
    tone: 'clay',
    title: 'STAR Partners Program',
    label: 'Potential partners',
    items: [
      'Local Government Units',
      'Schools and universities',
      'Business groups',
      'NGOs',
      'Cooperatives',
      'Chambers of commerce',
      'Professional organizations',
      'Youth organizations',
      'MSME groups',
    ],
  },
  {
    number: 40,
    section: 'Impact',
    kind: 'list',
    tone: 'teal',
    title: 'PICPA as a Community Partner',
    label: 'PICPA should be seen as a',
    items: [
      'Trusted resource',
      'Technical expert',
      'Governance partner',
      'Financial literacy advocate',
      'Community builder',
      'Professional voice',
      'Institutional support partner',
    ],
  },
  {
    number: 41,
    section: 'Impact',
    kind: 'list',
    tone: 'plum',
    title: 'Professional Engagement Opportunities',
    label: 'Examples',
    dense: true,
    items: [
      'Resource speakers for LGUs',
      'Financial literacy trainers for communities',
      'SME advisory clinics',
      'Cooperative governance training',
      'School career talks',
      'Entrepreneurship mentoring',
      'Participation in local policy and governance discussions where appropriate',
      'Technical support for transparency and accountability initiatives',
      'Collaboration with independent audit or advisory committees where legally and ethically appropriate',
    ],
  },
  {
    number: 42,
    section: 'Recognition',
    kind: 'list',
    tone: 'leaf',
    title: 'STAR Recognition Program',
    label: 'Suggested awards',
    items: [
      'Membership Growth Champion',
      'Best Retention Program',
      'Most Innovative Chapter',
      'Best Young CPA Initiative',
      'Community Impact Award',
      'Membership Excellence Award',
      'STAR Standard Bearer Award',
      'Outstanding Membership Ambassador',
    ],
  },
  {
    number: 43,
    section: 'Recognition',
    kind: 'list',
    tone: 'gold',
    title: 'Wall of Excellence',
    label: 'Recognize',
    items: [
      'Outstanding CPAs',
      'Board topnotchers',
      'Long-time members',
      'Community leaders',
      'Outstanding volunteers',
      'Emerging young CPA leaders',
      'CPA entrepreneurs',
      'Government CPA leaders',
      'Academe contributors',
    ],
  },
  {
    number: 44,
    section: 'Recognition',
    kind: 'list',
    tone: 'forest',
    title: 'Celebrate Membership Milestones',
    label: 'Recognize members for',
    items: [
      '5 years',
      '10 years',
      '25 years',
      '40 years',
      'Lifetime membership',
      'Legacy leadership',
      'Outstanding volunteer service',
    ],
  },
  {
    number: 45,
    section: 'Region Role',
    kind: 'cloud',
    tone: 'clay',
    title: 'The Role of the Region',
    lead: 'The Region should help chapters succeed.',
    items: ['Equip', 'Empower', 'Inspire', 'Connect', 'Support', 'Recognize'],
    note: 'The Region should not merely monitor chapters.',
  },
  {
    number: 46,
    section: 'Region Role',
    kind: 'list',
    tone: 'teal',
    title: 'Regional Membership Playbook',
    label: 'Provide chapters with',
    dense: true,
    items: [
      'Recruitment templates',
      'Welcome packet templates',
      'Re-invitation packet templates',
      'Membership recovery messages',
      'Social media content templates',
      'STAR ID partnership templates',
      'Community impact activity guides',
      'Best practice examples',
      'Dashboard templates',
    ],
  },
  {
    number: 47,
    section: 'Region Role',
    kind: 'list',
    tone: 'plum',
    title: 'Chapter Incubation Program',
    lead: 'Strong chapters mentor developing chapters.',
    label: 'Share',
    items: [
      'Membership strategies',
      'Activity formats',
      'Communication practices',
      'Engagement models',
      'Partnership approaches',
      'STAR ID implementation practices',
      'Digital page content examples',
    ],
  },
  {
    number: 48,
    section: 'Region Role',
    kind: 'list',
    tone: 'leaf',
    title: 'Membership Innovation Grants',
    label: 'Small grants may support',
    items: [
      'Membership drives',
      'Young CPA programs',
      'Community impact projects',
      'Digital initiatives',
      'STAR ID partnership development',
      'Visibility and branding initiatives',
      'Welcome and re-invitation packets',
    ],
  },
  {
    number: 49,
    section: 'Region Role',
    kind: 'list',
    tone: 'gold',
    title: 'Strategic Membership Initiatives Summary',
    dense: true,
    columns: 2,
    items: [
      'Every CPA Personally Invited',
      'STAR Welcome and Re-Invitation Packet',
      'STAR Sponsorship Program',
      'STAR Connect Mentorship',
      'STAR ID',
      'STAR Standard Bearers',
      'STAR Stories',
      'PICPA STAR Page',
      'STAR Communities',
      'Every Member Has a Role',
      'Membership Recovery Program',
      'STAR Community Impact Program',
      'STAR Partners Program',
      'STAR Advocacy and Visibility Program',
      'Regional Membership Playbook',
      'Membership Excellence Awards',
    ],
  },
  {
    number: 50,
    section: 'Action',
    kind: 'groups',
    tone: 'forest',
    title: 'Membership Recovery Program',
    groups: [
      {
        title: 'Reconnect with',
        items: [
          'Lapsed members',
          'Inactive members',
          'Formerly active members',
          'Members who renewed but no longer participate',
        ],
      },
      {
        title: 'Ask',
        featured: 'How can we welcome you back?',
        items: [],
      },
      {
        title: 'Use',
        items: [
          'Personal calls',
          'Short surveys',
          'Re-invitation packets',
          'Invitation messages',
          'Fellowship or reactivation events',
        ],
      },
    ],
  },
  {
    number: 51,
    section: 'Action',
    kind: 'list',
    tone: 'clay',
    title: 'Membership Dashboard',
    label: 'Track',
    dense: true,
    items: [
      'New members',
      'Renewal rate',
      'Participation rate',
      'Young CPA membership growth',
      'Recovered members',
      'STAR ID partners',
      'Community impact activities',
      'Visibility initiatives',
      'Welcome packets distributed',
      'Re-invitation packets distributed',
      'STAR Page engagement',
    ],
    note: 'Data should be used for coaching, not criticism.',
  },
  {
    number: 52,
    section: 'Action',
    kind: 'list',
    tone: 'teal',
    title: '90-Day Chapter Challenge',
    label: 'Each chapter commits to',
    items: [
      'One recruitment initiative',
      'One retention initiative',
      'One engagement initiative',
      'One STAR ID partner',
      'One community impact project',
      'One visibility project',
      'One welcome or re-invitation packet rollout',
    ],
  },
  {
    number: 53,
    section: 'Action',
    kind: 'acronym',
    tone: 'plum',
    title: 'STAR Region Membership Blueprint',
    items: [
      [
        'S',
        'Strengthen Membership',
        'STAR ID, sponsorship, recruitment, retention, welcome and re-invitation packets',
      ],
      ['T', 'Train and Transform', 'Mentorship, learning, leadership, young CPA development'],
      ['A', 'Advance the Profession', 'Advocacy, visibility, community impact, partnerships'],
      ['R', 'Recognize and Reward', 'Awards, member stories, milestones, belonging'],
    ],
  },
  {
    number: 54,
    section: 'Close',
    kind: 'cloud',
    tone: 'leaf',
    title: 'Final Message',
    lead: 'Membership is more than dues.',
    label: 'Membership is:',
    items: ['Value', 'Connection', 'Opportunity', 'Visibility', 'Belonging', 'Impact', 'Identity'],
  },
  {
    number: 55,
    section: 'Close',
    kind: 'statement',
    tone: 'gold',
    title: 'Together, We Build STAR',
    emphasis: 'finale',
    statements: [
      'When CPAs see value, they join.',
      'When CPAs build relationships, they stay.',
      'When CPAs feel they belong, they lead.',
      'When PICPA becomes visible and relevant in the community, membership growth becomes a natural outcome.',
      'Together, let us build a STAR Region where every chapter shines and every CPA proudly belongs.',
    ],
  },
]
